[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-compiler-builtins = "0.1.0"

[dev-dependencies]
mollusk-svm = "0.16.0"
solana-instruction = "4.0.0"

[profile.release]
overflow-checks = true
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
